version: '3.8'

services:
  # 币安公告机器人主服务
  bn-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bn-bot
    restart: unless-stopped
    
    # 环境变量配置
    env_file:
      - .env
    
    # 端口映射
    ports:
      - "${PORT:-5010}:5010"
    
    # 数据卷映射
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    
    # 网络配置
    networks:
      - bn-network

# 网络
networks:
  bn-network:
    driver: bridge